// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1x0zBAW6LzCRGhS72jjLGbbc0Bq4RQg',
    appId: '1:1058394873144:web:7edbc787a364274095f5cd',
    messagingSenderId: '1058394873144',
    projectId: 'todolistapp-5e674',
    authDomain: 'todolistapp-5e674.firebaseapp.com',
    storageBucket: 'todolistapp-5e674.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPN-iPl3NcvDE0mOvnOEbFZlEvtMKJ4k',
    appId: '1:1058394873144:android:0dc4bf379718c69395f5cd',
    messagingSenderId: '1058394873144',
    projectId: 'todolistapp-5e674',
    storageBucket: 'todolistapp-5e674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpW-Y8oNbkUd--_lfCbT5uc83s_g2_V8I',
    appId: '1:1058394873144:ios:f848554942ed725795f5cd',
    messagingSenderId: '1058394873144',
    projectId: 'todolistapp-5e674',
    storageBucket: 'todolistapp-5e674.appspot.com',
    iosBundleId: 'com.example.todoliseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpW-Y8oNbkUd--_lfCbT5uc83s_g2_V8I',
    appId: '1:1058394873144:ios:f848554942ed725795f5cd',
    messagingSenderId: '1058394873144',
    projectId: 'todolistapp-5e674',
    storageBucket: 'todolistapp-5e674.appspot.com',
    iosBundleId: 'com.example.todoliseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN1x0zBAW6LzCRGhS72jjLGbbc0Bq4RQg',
    appId: '1:1058394873144:web:7d9c4bf2d823b29595f5cd',
    messagingSenderId: '1058394873144',
    projectId: 'todolistapp-5e674',
    authDomain: 'todolistapp-5e674.firebaseapp.com',
    storageBucket: 'todolistapp-5e674.appspot.com',
  );
}
